### ISSUE TITLE
Console is throwing an error related to dash_renderer making app unresponsive.

### ISSUE THREAD

**Issue by sorenwacker** [LewisResearchGroup/ms-mint-app#44]
Observed when opening the metadata tab:

```
dash_renderer.v2_8_1m1678408876.min.js:2 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at dash_renderer.v2_8_1m1678408876.min.js:2:61093
    at Array.map (<anonymous>)
    at dash_renderer.v2_8_1m1678408876.min.js:2:61054
    at e (dash_renderer.v2_8_1m1678408876.min.js:2:39574)
    at dash_renderer.v2_8_1m1678408876.min.js:2:61195
    at e (dash_renderer.v2_8_1m1678408876.min.js:2:39574)
    at dash_renderer.v2_8_1m1678408876.min.js:2:137146
    at dash_renderer.v2_8_1m1678408876.min.js:2:59193
    at dash_renderer.v2_8_1m1678408876.min.js:2:47959
```

**Comment by sorenwacker** [comment]
It happens when a metadata file is uploaded with wrong columns. Need to investigate this more to reproduce it.

**Comment by sorenwacker** [comment]
Not happening any more.
